//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientsView1
    {
        public int ClientId { get; set; }
        public string НазваниеКлиента { get; set; }
        public string Улица { get; set; }
        public int Дом { get; set; }
        public Nullable<int> Корпус { get; set; }
        public Nullable<int> Строение { get; set; }
        public Nullable<int> Оффис { get; set; }
        public string Телефон { get; set; }
        public Nullable<System.DateTime> ДоговорИстекает { get; set; }
    }
}
